__author__ = 'brsch'

fantrax_to_fangraphs_teams = {
    '(N/A)': '',
    'ARI': 'Diamondbacks',
    'ATL': 'Braves',
    'BAL': 'Orioles',
    'BOS': 'Red Sox',
    'CHC': 'Cubs',
    'CHW': 'White Sox',
    'CIN': 'Reds',
    'CLE': 'Indians',
    'COL': 'Rockies',
    'DET': 'Tigers',
    'HOU': 'Astros',
    'KC': 'Royals',
    'LAA': 'Angels',
    'LAD': 'Dodgers',
    'MIA': 'Marlins',
    'MIL': 'Brewers',
    'MIN': 'Twins',
    'NYM': 'Mets',
    'NYY': 'Yankees',
    'OAK': 'Athletics',
    'PHI': 'Phillies',
    'PIT': 'Pirates',
    'SD': 'Padres',
    'SEA': 'Mariners',
    'SF': 'Giants',
    'STL': 'Cardinals',
    'TB': 'Rays',
    'TEX': 'Rangers',
    'TOR': 'Blue Jays',
    'WAS': 'Nationals'
    }

fx_to_fg_name_conversions = {
    'Lance McCullers Jr.': ('Lance', 'McCullers'),
    'Shin-soo Choo': ('Shin-Soo', 'Choo'),
    'Yuli Gurriel': ('Yulieski', 'Gurriel'),
    'Nicholas Castellanos': ('Nick', 'Castellanos'),
    'Michael A. Taylor': ('Michael', 'Taylor'),
    'J.C. Ramirez': ('JC', 'Ramirez'),
    'Kike Hernandez': ('Kik\xc3\xa9', 'Hernandez'),
    'AJ Ramos': ('A.J.', 'Ramos'),
    'Jake Faria': ('Jacob', 'Faria'),
    'JT Riddle': ('J.T.', 'Riddle'),
    'Norichika Aoki': ('Nori', 'Aoki'),
    'Jose M. Torres': ('Jose', 'Torres'),
    'Nate Karns': ('Nathan', 'Karns'),
    'Daniel Vogelbach': ('Dan', 'Vogelbach'),
    'Eric Young Jr.': ('Eric', 'Young'),
    'Mike Martinez': ('Michael', 'Martinez'),
    'Cameron Perkins': ('Cam', 'Perkins'),
    'Sam Tuivailala': ('Samuel', 'Tuivailala'),
    'Jorge De La Rosa': ('Jorge', 'de la Rosa'),
    'Jake Junis': ('Jakob', 'Junis'),
    'Zack Granite': ('Zach', 'Granite'),
    'Dwight Smith Jr.': ('Dwight', 'Smith'),
    'Greg Bird': ('Gregory', 'Bird'),
    'Matthew Boyd': ('Matt', 'Boyd'),
    'Rubby De La Rosa': ('Rubby', 'de la Rosa'),
    'Mark Leiter Jr.': ('Mark', 'Leiter')
    }

starting_roster = {
    'C': 2,
    '1B': 1,
    '2B': 1,
    '3B': 1,
    'SS': 1,
    'CI': 1,
    'MI': 1,
    'OF': 5,
    'UT': 2,

    'SP': 3,
    'RP': 2,
    'P': 3
}

pos_scalar = {
    'C': 1.00001,
    '1B': 1.00001,
    '2B': 1.00001,
    '3B': 1.00001,
    'SS': 1.00001,
    'CI': 1,
    'MI': 1,
    'OF': 1.00001,
    'UT': 1,

    'SP': 1.00001,
    'RP': 1.00001,
    'P': 1
}
ordered_pos = ['C', '1B', '2B', '3B', 'SS', 'CI', 'MI', 'OF', 'UT', 'SP', 'RP', 'P']

games_per_pos = {
    'C': 81,
    '1B': 81,
    '2B': 81,
    '3B': 81,
    'SS': 81,
    'CI': 81,
    'MI': 81,
    'OF': 81,
    'UT': 81,
    'SP': 16,
    'RP': 81,
    'P':  16}

nonfantrax_playerids = [
    '4182', '650', '3441', 'sa657984', 'sa3001224'
    ]

fg_to_fx = {
    ('Fernando Romero', '(N/A)'): ('Romero, Fernando', 'MIN'),
    ('Jacob Hannemann', '(N/A)'): ('Hannemann, Jacob', 'CHC'),
    ('Alejandro De Aza', '(N/A)'): ('De Aza, Alejandro', 'WAS'),
    ('Dylan Cozens', '(N/A)'): ('Cozens, Dylan', 'PHI'),
    ('Henderson Alvarez', '(N/A)'): ('Alvarez, Henderson', 'OAK'),
    ('Nick Kingham', '(N/A)'): ('Kingham, Nick', 'PIT'),
    ('Kyle Farmer', '(N/A)'): ('Farmer, Kyle', 'LAD'),
    ('Justin Morneau', '(N/A)'): ('Morneau, Justin', 'CHW'),
    ('Tyler Ladendorf', '(N/A)'): ('Ladendorf, Tyler', 'CHW'),
    ('Melvin Upton Jr.', 'SF'): ('Upton Jr., Melvin', '(N/A)'),
    ('Taylor Guerrieri', '(N/A)'): ('Guerrieri, Taylor', 'TB'),
    ('Tyler Beede', '(N/A)'): ('Beede, Tyler', 'SF'),
    ('Alfredo Gonzalez', '(N/A)'): ('Gonzalez, Alfredo', 'HOU'),
    ('Rhys Hoskins', '(N/A)'): ('Hoskins, Rhys', 'PHI'),
    ('Jacob Rhame', '(N/A)'): ('Rhame, Jacob', 'LAD'),
    ('Tomas Nido', '(N/A)'): ('Nido, Tomas', 'NYM'),
    ('Austin Nola', '(N/A)'): ('Nola, Austin', 'MIA'),
    ('Duane Underwood Jr.', '(N/A)'): ('Underwood, Duane', 'CHC'),
    ('Daniel Palka', '(N/A)'): ('Palka, Daniel', 'MIN'),
    ('Paul Clemens', '(N/A)'): ('Clemens, Paul', 'MIN'),
    ('Clayton Blackburn', '(N/A)'): ('Blackburn, Clayton', 'TEX'),
    ('Sam Moll', '(N/A)'): ('Moll, Sam', 'COL'),
    ('Austin Voth', '(N/A)'): ('Voth, Austin', 'WAS'),
    ('Marlon Byrd', '(N/A)'): ('Byrd, Marlon', 'CLE'),
    ('Ronald Guzman', '(N/A)'): ('Guzman, Ronald', 'TEX'),
    ('Jack Flaherty', '(N/A)'): ('Flaherty, Jack', 'STL'),
    ('Jack Reinheimer', '(N/A)'): ('Reinheimer, Jack', 'ARI'),
    ('Nick Williams', '(N/A)'): ('Williams, Nick', 'PHI'),
    ('Scott Kingery', '(N/A)'): ('Kingery, Scott', 'PHI'),
    ('Connor Sadzeck', '(N/A)'): ('Sadzeck, Connor', 'TEX'),
    ('Mitch Garver', '(N/A)'): ('Garver, Mitchell', 'MIN'),
    ('Keury Mella', '(N/A)'): ('Mella, Keury', 'CIN'),
    ('Engelb Vielma', '(N/A)'): ('Vielma, Engelb', 'MIN'),
    ('Alberto Tirado', '(N/A)'): ('Tirado, Alberto', 'PHI'),
    ('Conor Mullee', '(N/A)'): ('Mullee, Conor', 'CHC'),
    ('Sean Doolittle', 'WAS'): ('Doolittle, Sean', 'OAK'),
    ('Ozzie Albies', '(N/A)'): ('Albies, Ozzie', 'ATL'),
    ('Cam Gallagher', '(N/A)'): ('Gallagher, Cameron', 'KC'),
    ('J.B. Shuck', 'CHW'): ('Shuck, J.B.', 'MIN'),
    ('Brent Honeywell', '(N/A)'): ('Honeywell, Brent', 'TB'),
    ('J.P. Crawford', '(N/A)'): ('Crawford, J.P.', 'PHI'),
    ('Sandy Alcantara', '(N/A)'): ('Alcantara, Sandy', 'STL'),
    ('Amed Rosario', '(N/A)'): ('Rosario, Amed', 'NYM'),
    ('Tyler Matzek', 'COL'): ('Matzek, Tyler', 'CHW'),
    ('Rafael Devers', '(N/A)'): ('Devers, Rafael', 'BOS'),
    ('Ryan Cordell', '(N/A)'): ('Cordell, Ryan', 'MIL'),
    ('Harrison Bader', '(N/A)'): ('Bader, Harrison', 'STL'),
    ('Jimmy Cordero', '(N/A)'): ('Cordero, Jimmy', 'PHI'),
    ('Rowdy Tellez', '(N/A)'): ('Tellez, Rowdy', 'TOR'),
    ('Richard Urena', '(N/A)'): ('Urena, Richard', 'TOR'),
    ('Aaron Barrett', '(N/A)'): ('Barrett, Aaron', 'WAS'),
    ('Chase Johnson', '(N/A)'): ('Johnson, Chase', 'SF'),
    ('Taylor Williams', '(N/A)'): ('Williams, Taylor', 'MIL'),
    ('Anthony Santander', '(N/A)'): ('Santander, Anthony', 'BAL'),
    ('Jarrod Parker', '(N/A)'): ('Parker, Jarrod', 'OAK'),
    ('Christian Villanueva', '(N/A)'): ('Villanueva, Christian', 'SD'),
    ('Dietrich Enns', '(N/A)'): ('Enns, Dietrich', 'NYY'),
    ('Marcos Molina', '(N/A)'): ('Molina, Marcos', 'NYM'),
    ('Harold Ramirez', '(N/A)'): ('Ramirez, Harold', 'TOR'),
    ('Adam Wilk', 'MIN'): ('Wilk, Adam', '(N/A)'),
    ('Kik\xc3\xa9 Hernandez', 'LAD'): ('Hernandez, Kike', 'LAD'),
    ('Nathan Karns', 'KC'): ('Karns, Nate', 'KC'),
    ('Ryan LaMarre', 'OAK'): ('LaMarre, Ryan', '(N/A)'),
    ('Sean Gilmartin', 'NYM'): ('Gilmartin, Sean', 'STL'),
    ('Antonio Bastardo', 'PIT'): ('Bastardo, Antonio', '(N/A)'),
    ('Jake Buchanan', 'CIN'): ('Buchanan, Jake', 'ARI'),
    ('Derek Norris', 'TB'): ('Norris, Derek', '(N/A)'),
    ('Chad Qualls', 'COL'): ('Qualls, Chad', '(N/A)'),
    ('Tom Wilhelmsen', 'ARI'): ('Wilhelmsen, Tom', 'MIL'),
    ('Jake Esch', 'SD'): ('Esch, Jake', '(N/A)'),
    ('Yulieski Gurriel', 'HOU'): ('Gurriel, Yuli', 'HOU'),
    ('Nori Aoki', 'HOU'): ('Aoki, Norichika', 'HOU'),
    ('Jeanmar Gomez', 'PHI'): ('Gomez, Jeanmar', 'MIL'),
    ('Luis Sardinas', 'SD'): ('Sardinas, Luis', 'BAL'),
    ('Jason Wheeler', 'MIN'): ('Wheeler, Jason', 'BAL'),
    ('Glenn Sparkman', 'TOR'): ('Sparkman, Glenn', '(N/A)'),
    ('Stephen Cardullo', '(N/A)'): ('Cardullo, Stephen', 'COL'),
    ('William Cuevas', 'DET'): ('Cuevas, William', 'MIA'),
    ('Drew Stubbs', 'SF'): ('Stubbs, Drew', 'TEX'),
    ('Chris Young', 'KC'): ('Young, Chris', 'BOS'),
    ('Michael Martinez', 'TB'): ('Martinez, Michael', 'CLE'),
    ('Zac Rosscup', '(N/A)'): ('Rosscup, Zac', 'COL'),
    ('Lucas Harrell', '(N/A)'): ('Harrell, Lucas', 'TOR'),
    ('Bryan Morris', 'SF'): ('Morris, Bryan', '(N/A)'),
    ('Francisco Rodriguez', 'DET'): ('Rodriguez, Francisco', '(N/A)'),
    ('Chris Carter', 'NYY'): ('Carter, Chris', '(N/A)'),
    ('Jhonny Peralta', 'STL'): ('Peralta, Jhonny', '(N/A)'),
    ('Mike Hauschild', 'TEX'): ('Hauschild, Mike', '(N/A)'),
    ('Mat Latos', 'TOR'): ('Latos, Mat', '(N/A)'),
    ('Edwin Jackson', 'BAL'): ('Jackson, Edwin', 'WAS'),
    ('Grant Green', 'WAS'): ('Green, Grant', 'CHW'),
    ('Josh Lindblom', 'PIT'): ('Lindblom, Josh', '(N/A)'),
    ('Jonathan Broxton', 'STL'): ('Broxton, Jonathan', '(N/A)'),
    ('Nick Franklin', 'MIL'): ('Franklin, Nick', 'LAA'),
    ('Tommy Layne', 'NYY'): ('Layne, Tommy', '(N/A)'),
    ('Emilio Bonifacio', 'ATL'): ('Bonifacio, Emilio', '(N/A)'),
    ('Aaron Hill', 'SF'): ('Hill, Aaron', '(N/A)'),
    ('Edmundo Sosa', '(N/A)'): ('Sosa, Edmundo', 'STL'),
    ('Jose Marmolejos', '(N/A)'): ('Marmolejos, Jose', 'WAS'),
    ('Yefry Ramirez', '(N/A)'): ('Ramirez, Yefrey', 'NYY'),
    ('Dawel Lugo', '(N/A)'): ('Lugo, Dawel', 'ARI'),
    ('Ramon Cabrera', '(N/A)'): ('Cabrera, Ramon', 'MIA'),
    ('Lucas Sims', '(N/A)'): ('Sims, Lucas', 'ATL'),
    ('Aristides Aquino', '(N/A)'): ('Aquino, Aristides', 'CIN'),
    ('Jorge Mateo', '(N/A)'): ('Mateo, Jorge', 'NYY'),
    ('Samir Duenez', '(N/A)'): ('Duenez, Samir', 'KC'),
    ('Bubba Starling', '(N/A)'): ('Starling, Bubba', 'KC'),
    ('Chris Lee', '(N/A)'): ('Lee, Chris', 'BAL'),
    ('Brandon Woodruff', '(N/A)'): ('Woodruff, Brandon', 'MIL'),
    ('Clay Holmes', '(N/A)'): ('Holmes, Clay', 'PIT'),
    ('Jaime Schultz', '(N/A)'): ('Schultz, Jaime', 'TB'),
    ('Blake Treinen', 'OAK'): ('Treinen, Blake', 'WAS'),
    ('Kyle Zimmer', '(N/A)'): ('Zimmer, Kyle', 'KC'),
    ('Ryan Madson', 'WAS'): ('Madson, Ryan', 'OAK'),
    ('Eliezer Alvarez', '(N/A)'): ('Alvarez, Eliezer', 'STL'),
    ('Steve Tolleson', 'TOR'): ('Tolleson, Steve', 'KC'),
    ('Keyvius Sampson', '(N/A)'): ('Sampson, Keyvius', 'MIA'),
    ('Yency Almonte', '(N/A)'): ('Almonte, Yency', 'COL'),
    ('Anthony Banda', '(N/A)'): ('Banda, Anthony', 'ARI'),
    ('Reyes Moronta', '(N/A)'): ('Moronta, Reyes', 'SF'),
    ('Chris Flexen', '(N/A)'): ('Flexen, Chris', 'NYM'),
    ('Willy Adames', '(N/A)'): ('Adames, Willy', 'TB'),
    ('Mel Rojas Jr.', '(N/A)'): ('Rojas Jr., Mel', 'ATL'),
    ('Francisco Mejia', '(N/A)'): ('Mejia, Francisco', 'CLE'),
    ('Kevin Jepsen', '(N/A)'): ('Jepsen, Kevin', 'WAS'),
    ('Nick Gordon', '(N/A)'): ('Gordon, Nick', 'MIN'),
    ('Zach Jemiola', '(N/A)'): ('Jemiola, Zach', 'COL'),
    ('Austin Meadows', '(N/A)'): ('Meadows, Austin', 'PIT'),
    ('Abraham Almonte', '(N/A)'): ('Almonte, Abraham', 'CLE'),
    ('Mason Melotakis', '(N/A)'): ('Melotakis, Mason', 'MIN'),
    ('Breyvic Valera', '(N/A)'): ('Valera, Breyvic', 'STL'),
    ('Chance Adams', '(N/A)'): ('Adams, Chance', 'NYY'),
    ('Nick Travieso', '(N/A)'): ('Travieso, Nick', 'CIN'),
    ('Matt Skole', '(N/A)'): ('Skole, Matt', 'WAS'),
    ('Jake Bauers', '(N/A)'): ('Bauers, Jake', 'TB'),
    ('Erick Fedde', '(N/A)'): ('Fedde, Erick', 'WAS'),
    ('D.J. Peterson', '(N/A)'): ('Peterson, D.J.', 'SEA'),
    ('Kevin Gadea', '(N/A)'): ('Gadea, Kevin', 'TB'),
    ('Zach Walters', 'LAD'): ('Walters, Zach', 'KC'),
    ('Max Fried', '(N/A)'): ('Fried, Max', 'ATL'),
    ('Jesus Liranzo', '(N/A)'): ('Liranzo, Jesus', 'BAL'),
    ('Rowan Wick', '(N/A)'): ('Wick, Rowan', 'STL'),
    ('Rayan Gonzalez', '(N/A)'): ('Gonzalez, Rayan', 'COL'),
    ('Jose Ruiz', '(N/A)'): ('Ruiz, Jose', 'SD'),
    }
