__author__ = 'brsch'

fantrax_to_fangraphs_teams = {
    '(N/A)': '',
    'ARI': 'Diamondbacks',
    'ATL': 'Braves',
    'BAL': 'Orioles',
    'BOS': 'Red Sox',
    'CHC': 'Cubs',
    'CHW': 'White Sox',
    'CIN': 'Reds',
    'CLE': 'Indians',
    'COL': 'Rockies',
    'DET': 'Tigers',
    'HOU': 'Astros',
    'KC': 'Royals',
    'LAA': 'Angels',
    'LAD': 'Dodgers',
    'MIA': 'Marlins',
    'MIL': 'Brewers',
    'MIN': 'Twins',
    'NYM': 'Mets',
    'NYY': 'Yankees',
    'OAK': 'Athletics',
    'PHI': 'Phillies',
    'PIT': 'Pirates',
    'SD': 'Padres',
    'SEA': 'Mariners',
    'SF': 'Giants',
    'STL': 'Cardinals',
    'TB': 'Rays',
    'TEX': 'Rangers',
    'TOR': 'Blue Jays',
    'WAS': 'Nationals'
    }

fx_to_fg_name_conversions = {
    'Lance McCullers Jr.': ('Lance', 'McCullers'),
    'Shin-soo Choo': ('Shin-Soo', 'Choo'),
    'Yuli Gurriel': ('Yulieski', 'Gurriel'),
    'Nicholas Castellanos': ('Nick', 'Castellanos'),
    'Michael A. Taylor': ('Michael', 'Taylor'),
    'J.C. Ramirez': ('JC', 'Ramirez'),
    'Kike Hernandez': ('Kik\xc3\xa9', 'Hernandez'),
    'AJ Ramos': ('A.J.', 'Ramos'),
    'Jake Faria': ('Jacob', 'Faria'),
    'JT Riddle': ('J.T.', 'Riddle'),
    'Norichika Aoki': ('Nori', 'Aoki'),
    'Jose M. Torres': ('Jose', 'Torres'),
    'Nate Karns': ('Nathan', 'Karns'),
    'Daniel Vogelbach': ('Dan', 'Vogelbach'),
    'Eric Young Jr.': ('Eric', 'Young'),
    'Mike Martinez': ('Michael', 'Martinez'),
    'Cameron Perkins': ('Cam', 'Perkins'),
    'Sam Tuivailala': ('Samuel', 'Tuivailala'),
    'Jorge De La Rosa': ('Jorge', 'de la Rosa'),
    'Jake Junis': ('Jakob', 'Junis'),
    'Zack Granite': ('Zach', 'Granite'),
    'Dwight Smith Jr.': ('Dwight', 'Smith'),
    'Greg Bird': ('Gregory', 'Bird'),
    'Matthew Boyd': ('Matt', 'Boyd'),
    'Rubby De La Rosa': ('Rubby', 'de la Rosa'),
    'Mark Leiter Jr.': ('Mark', 'Leiter')
    }
